package com.smartdelivery.platform.openapi;

import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.security.SecurityRequirement;
import io.swagger.v3.oas.models.security.SecurityScheme;
import io.swagger.v3.oas.models.servers.Server;

import java.util.List;

/**
 * Builds the {@link OpenAPI} document header each service serves at
 * {@code /v3/api-docs}. The paths and schemas are still generated by springdoc from the
 * real controllers; only the parts springdoc cannot infer are set here.
 *
 * <p>The {@code servers} entry is the one that earns this class its existence. Left to
 * itself, springdoc derives the server URL from the request that fetched the document --
 * and in this platform that request arrives <em>from api-gateway</em>, so the document
 * would advertise {@code http://order-service:8084}: a hostname that exists only on the
 * compose network and resolves to nothing in the reader's browser. Swagger UI would
 * render perfectly and then fail on every "Try it out" with an opaque network error.
 * Pinning the server to the gateway's public URL is what makes the aggregated UI
 * usable rather than merely present.
 *
 * <p>The bearer security scheme is declared here for the same reason: every endpoint in
 * this platform except registration and login needs a JWT (docs/security.md), so a
 * Swagger UI with no Authorize button can only ever demonstrate 401s.
 */
public final class PlatformOpenApiConfiguration {

    public static final String BEARER_SCHEME_NAME = "bearerAuth";

    private PlatformOpenApiConfiguration() {
    }

    public static OpenAPI build(PlatformOpenApiProperties properties, String applicationName) {
        String title = properties.title() != null && !properties.title().isBlank()
                ? properties.title()
                : applicationName;

        SecurityScheme bearer = new SecurityScheme()
                .type(SecurityScheme.Type.HTTP)
                .scheme("bearer")
                .bearerFormat("JWT")
                .description("""
                        An RS256 access token from POST /api/v1/auth/login, verified against \
                        user-service's published JWKS (ADR 007). Paste the token value only, \
                        without the "Bearer " prefix -- Swagger UI adds it.""");

        return new OpenAPI()
                .info(new Info()
                        .title(title)
                        .version(properties.version())
                        .description(properties.description()))
                // A single server, and it is the gateway: there is deliberately no entry
                // for the service's own port, because reaching a service directly bypasses
                // the gateway's routing, correlation id, and rate limiting, and offering it
                // in a dropdown would present that as a supported way in.
                .servers(List.of(new Server()
                        .url(properties.publicUrl())
                        .description("api-gateway (the only supported entry point)")))
                .components(new Components().addSecuritySchemes(BEARER_SCHEME_NAME, bearer))
                .addSecurityItem(new SecurityRequirement().addList(BEARER_SCHEME_NAME));
    }
}
