CREATE TABLE roles (
    id   BIGSERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO roles (name) VALUES
    ('CUSTOMER'),
    ('ADMIN'),
    ('WAREHOUSE_MANAGER'),
    ('DELIVERY_AGENT');
